set=set()

no=int(input("Enter your no: "))
set.add(no)
no=int(input("Enter your no: "))
set.add(no)
no=int(input("Enter your no: "))
set.add(no)
no=int(input("Enter your no: "))
set.add(no)
no=int(input("Enter your no: "))
set.add(no)
no=int(input("Enter your no: "))
set.add(no)
no=int(input("Enter your no: "))
set.add(no)
no=int(input("Enter your no: "))
set.add(no)

print(set)